Repository dubinc/dub, pull requests merged in 2024-10, with the labels that each got.

#1321 fix: add logo support to QR code API using <img> tag as a workaround
  apps/web/app/api/qr/route.tsx
  apps/web/lib/qr/api.tsx
  apps/web/lib/qr/types.ts
  apps/web/lib/qr/utils.tsx
  apps/web/lib/zod/schemas/qr.ts
  apps/web/package.json
  apps/web/ui/modals/link-qr-modal.tsx
  pnpm-lock.yaml
Labels: 🕹️ oss.gg

#1328 improved not found page
  apps/web/app/not-found.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#1333 fix: Allow users to "reactivate" their Dub subscription
  apps/web/app/api/workspaces/[idOrSlug]/billing/upgrade/route.ts
Labels: 🕹️ oss.gg, 🕹️ 300 points

#1435 fix: redirection to login page on cancelling of consent of oauth providers
  apps/web/lib/auth/options.ts
Labels: 🕹️ oss.gg, 🕹️ 150 points

#1482 fix: add proper messages
  apps/web/app/app.dub.co/(auth)/login/form.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#1573 Fix : Images getting cropped when help center is active in small devices
  apps/web/ui/shared/new-background.tsx
Labels: 🕹️ oss.gg, 🕹️ 150 points

#1661 fix(api): reorder `trim()` method calls in Zod schema
  apps/web/lib/zod/schemas/tags.ts
  apps/web/lib/zod/schemas/utm.ts
Labels: bug, 🕹️ oss.gg, 🕹️ 300 points

#1644 refactor(ui): create and use "useCopyToClipboard" hook with configurable timeout
  apps/web/app/admin.dub.co/(dashboard)/components/user-info.tsx
  apps/web/app/admin.dub.co/(dashboard)/layout.tsx
  apps/web/app/app.dub.co/(dashboard)/[slug]/settings/library/tags/tag-card.tsx
  apps/web/app/app.dub.co/(dashboard)/[slug]/settings/people/page-client.tsx
  apps/web/ui/analytics/events/events-table.tsx
  apps/web/ui/analytics/events/row-menu-button.tsx
  apps/web/ui/analytics/toggle.tsx
  apps/web/ui/domains/domain-card.tsx
  apps/web/ui/layout/sidebar/sidebar-nav.tsx
  apps/web/ui/links/link-controls.tsx
  apps/web/ui/modals/link-builder/index.tsx
  apps/web/ui/modals/link-qr-modal.tsx
  apps/web/ui/modals/scim-modal.tsx
  apps/web/ui/modals/share-dashboard-modal.tsx
  apps/web/ui/webhooks/webhook-events.tsx
  apps/web/ui/webhooks/webhook-header.tsx
  packages/ui/src/copy-button.tsx
  packages/ui/src/copy-text.tsx
  packages/ui/src/footer.tsx
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/use-copy-to-clipboard.tsx
  packages/ui/src/index.tsx
  packages/ui/src/nav-wordmark.tsx
  packages/ui/src/nav/nav.tsx
Labels: 🕹️ oss.gg, 🕹️ 750 points

#1620 fix(ui): modal scrolling behavior on mobile
  apps/web/ui/modals/add-edit-domain-modal.tsx
  apps/web/ui/modals/add-edit-token-modal.tsx
  apps/web/ui/modals/import-csv-modal/index.tsx
  apps/web/ui/modals/invite-teammate-modal.tsx
  apps/web/ui/modals/send-test-webhook-modal.tsx
  apps/web/ui/modals/transfer-domain-modal.tsx
  apps/web/ui/modals/transfer-link-modal.tsx
  packages/ui/src/modal.tsx
Labels: 🕹️ oss.gg, 🕹️ 750 points
